# Generated by Django 5.1.4 on 2024-12-30 14:42

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='描述')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='api.destination', verbose_name='目的地')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '行程',
                'verbose_name_plural': '行程',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='第几天')),
                ('date', models.DateField(verbose_name='日期')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='api.itinerary', verbose_name='所属行程')),
            ],
            options={
                'verbose_name': '行程日程',
                'verbose_name_plural': '行程日程',
                'ordering': ['day_number'],
                'unique_together': {('itinerary', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_location', models.CharField(blank=True, help_text='如果不是景点，可以填写自定义地点（如餐厅、酒店等）', max_length=200, verbose_name='自定义地点')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('transportation', models.CharField(blank=True, max_length=100, verbose_name='交通方式')),
                ('attraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_items', to='api.attraction', verbose_name='景点')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.itineraryday', verbose_name='所属日程')),
            ],
            options={
                'verbose_name': '行程项目',
                'verbose_name_plural': '行程项目',
                'ordering': ['start_time'],
            },
        ),
    ]
