# Generated by Django 5.1.4 on 2025-01-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_attractionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='country',
            field=models.CharField(default='中国', max_length=100, verbose_name='国家'),
        ),
        migrations.AddField(
            model_name='destination',
            name='province',
            field=models.CharField(blank=True, max_length=100, verbose_name='省份'),
        ),
    ]
