# Generated by Django 5.1.4 on 2025-01-07 14:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_destination_country_destination_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='long_description',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='详细描述'),
        ),
    ]
